### ISSUE TITLE
How to train more classes label instead of two？

### ISSUE THREAD

**Issue by xgyyao** [wgcban/ChangeFormer#29] opened 2022-08-01 07:17 UTC
Hi
I really appreciate your work.Now I want to train on changesim，a dataset with 4 classes label ，such as "missing","new","ratation","replaced object". I tried change n_class , but it didnt work. what should I do to train on a dataset which is more than 2 classes? thx~

**Comment by wgcban** [comment] 2022-08-01 11:51
@xgyyao If you have ``n`` number of classes as the output instead of 2 classes in my class, you basically need to set the default value of the ``--n_classes`` argument to ``n``, and the code should handle this automatically (though I haven't tried it, I received confirmation from multiple people that it did work!). Can you pls explain here why it didn't work and which errors you are getting with more details? I am happy to help you.

--Chaminda.

**Comment by xgyyao** [comment] 2022-08-01 12:03
> 

I got error like this:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/34907486/182143314-fcb4ac00-6656-45af-89a9-275b4ff02dda.png">
my label is rgb instead of gray.

**Comment by wgcban** [comment] 2022-08-01 12:32
@ Yes, Since your labels are in RGB, select only one channel out of 3 channels: ``A=A[:,:,:,:,0]``.

**Comment by xgyyao** [comment] 2022-08-01 14:25
> @ Yes, Since your labels are in RGB, select only one channel out of 3 channels in the dataset. I have already added a comment there to solve this issue in `Line 114` in the : [ChangeFormer](https://github.com/wgcban/ChangeFormer)/[datasets](https://github.com/wgcban/ChangeFormer/tree/main/datasets)/CD_dataset.py:
> 
> Add `label = label[:,:,0]` after `label = np.array(Image.open(L_path), dtype=np.uint8)`:
> 
> https://github.com/wgcban/ChangeFormer/blob/193743a351f7cc7b4674e896bd1387874bf4667d/datasets/CD_dataset.py#L114
> 
> I hope this will solve your error.

I tried like this:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/34907486/182167565-a42c751f-4705-4435-973f-558e1cc97879.png">
but got error below:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/34907486/182168085-64991463-6ba4-411f-ba60-1aa4c6c4503f.png">


so I change like this:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/34907486/182167809-0698e42c-9176-412c-8b74-7f7ed0506d18.png">
or like this:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/34907486/182169392-09ae9246-6d3a-42be-903d-8bae46995748.png">

but both got same error below:
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/34907486/182168952-ef76576a-fcd8-49a9-9a9f-aa9939ea0ed3.png">

waiting for your reply!

**Comment by wgcban** [comment] 2022-08-01 15:18
What is the size of the label at line 114 without any modification?

**Comment by xgyyao** [comment] 2022-08-02 02:24
> @xgyyao What is the size of the label at line 114 without any modification?

some are (330,330,3),the others are (330,330),maybe this cause the error?
<img width="179" alt="image" src="https://user-images.githubusercontent.com/34907486/182278044-b63867fc-f4bb-49d0-84df-8172c8060dc5.png">

**Comment by wgcban** [comment] 2022-08-02 02:52
Yes, Exactly. This is the cause of the error. So, this can be easily solved via simple ``if else`` statement.
'''
label = label[:,:,0] if label.ndim==3 else label=label
'''

**Comment by xgyyao** [comment] 2022-08-02 03:07
> label = label[:,:,0] if label.ndim==3 else label=label

it works! but I got another error, changesim dataset has 4 class label , add background is 5 class,right?  the error is like below:
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/34907486/182283225-760cc834-52e5-4ab7-b793-828189d179e5.png">

**Comment by xgyyao** [comment] 2022-08-02 03:37
> @xgyyao,
> 
> Yes, I think so... This is the cause of the error. So, this can be easily solved by a simple `if else` statement.
> 
> ```
> label = label[:,:,0] if label.ndim==3 else label=label
> ```

I print the max label , and do not set self.label_transform = "norm"
<img width="96" alt="image" src="https://user-images.githubusercontent.com/34907486/182286380-8a88e0f9-e0fd-426e-959d-fadd44718e07.png">

**Comment by wgcban** [comment] 2022-08-02 04:25
@xgyyao, I think there is an issue with your dataset. If you have five classes in the dataset, the maximum value should be 4, and the label can only take values from {0,1,2,3,4}. Because when computing the cross-entropy loss, that is how each class is recognized.  Therefore, I think you are missing something here...

**Comment by wgcban** [comment] 2022-08-02 04:27
@xgyyao, can you post here some example label images so that I can have a look?

**Comment by xgyyao** [comment] 2022-08-02 05:41
> @xgyyao, can you post here some example label images so that I can have a look? Also, just check whether they have a different encoding scheme for each class that you need to follow.
these are some example label images including 4 classes。
![1](https://user-images.githubusercontent.com/34907486/182300106-a8504d3e-92b9-4917-b8f3-cfc19e1dffa3.png)
![400](https://user-images.githubusercontent.com/34907486/182300127-7f5b1fa6-7a15-4ab4-9fd8-3812ae210133.png)

**Comment by xgyyao** [comment] 2022-08-02 07:10
> @xgyyao, can you post here some example label images so that I can have a look? Also, just check whether they have a different encoding scheme for each class that you need to follow.

I solved the question，because there are some classes  args unchangeable even if I switch the n_class.
thx for your kindness helping solve my question!

**Comment by wgcban** [comment] 2022-08-02 11:13
Since the problem is solved, I am closing this issue.

**Comment by wgcban** [comment] 2022-08-02 12:35
Since the problem is solved, I am closing this issue.

**Closed by wgcban** 2022-08-02 12:35 UTC
Labels: help wanted
